#!/usr/bin/env bash

SCRIPTDIR=$(dirname $0)

## If globally installed, avoid overriding pythonpath
# PYTHONPATH_ARG=
PYTHONPATH_ARG="--pythonpath=$SCRIPTDIR"

if [[ $# -lt 1 ]]; then
	echo "Usage: $0 USERNAME" >&2
	exit 1
fi

django-admin keycommand $PYTHONPATH_ARG --settings=moalinna.settings $1
