# Generated by Django 2.2 on 2020-02-17 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PubSSHKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keytype', models.CharField(max_length=32)),
                ('pubkey', models.BinaryField()),
                ('comment', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pubkey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('keytype', 'pubkey')},
            },
        ),
    ]
