# Generated by Django 2.2 on 2021-01-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorized_keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubsshkey',
            name='comment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
