# Generated by Django 2.2 on 2021-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorized_keys', '0002_auto_20210115_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubsshkey',
            name='keytype',
            field=models.CharField(choices=[('ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp256'), ('ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp384'), ('ecdsa-sha2-nistp521', 'ecdsa-sha2-nistp521'), ('ssh-ed25519', 'ssh-ed25519'), ('ssh-dss', 'ssh-dss'), ('ssh-rsa', 'ssh-rsa')], max_length=32),
        ),
    ]
